### ISSUE TITLE
rendermode does not exist in the current context

### ISSUE THREAD

**Issue by NguyenBaHoangKim** [dotnet/website-feedback#181]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/modify

### Operating system

windows

### Description

i dont know i follow the tutorial but its error

**Comment by stnikan** [comment]
I apologize for my English
"dotnet --info" did not work due to a conflict between two versions in different folders, try to check where "dotnet" is located.
![image](https://github.com/dotnet/website-feedback/assets/141735170/d29fa43b-116e-408c-a2c7-508af58fba9e)
If there are two possible paths, then an extra one has been installed .NET SDK
I deleted the additional version from the Program Files (x86) folder
After that, everything worked

**Comment by katiesavage** [comment]
To confirm, is it working now?

**Comment by mairaw** [comment]
The message above is not from the OP. @NguyenBaHoangKim can you give us more information about the error?

@stnikan you most likely were having an issue with PATH. I'm glad things are working now for you.
