### ISSUE TITLE
missing namespace

### ISSUE THREAD

**Issue by AlperenBaytimur** [dotnet/website-feedback#183]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create

### Operating system

windows

### More information about your system

Windows 11, intel core i7, and I used visual studio 2022

### Description

the problem is that it says that a namespace is missing, namely the name of my project, but the joke is, its referenced the right way in the code, so I have no idea what is going wrong to be honest

### dotnet --info

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'BlazorApp' could not be found (are you missing a using directive or an assembly reference?)	BlazorApp	C:\Informatica\Projecten\BlazorApp\Program.cs	1	N/A

**Comment by katiesavage** [comment]
Are you getting those errors in Visual Studio? Can you make sure your VS is up to date?

@danroth27 any other suggestions?

**Comment by danroth27** [comment]
@AlperenBaytimur It sounds like you hit an issue with the Visual Studio editor incorrectly reporting an issue with the code. You can check this by trying to build the project from the command-line using `dotnet build`. Assuming the project builds cleanly, you can try restarting Visual Studio to see if the issue resolves itself.

Since this issue is pretty old at this point, I'm going to go ahead and close it. But if you're still having issues, please let us know and we'll reopen the issue for investigation.

@phil-allen-msft @leslierichardson95 FYI.
