### ISSUE TITLE
Web frontend

### ISSUE THREAD

**Issue by captainenkay** [dotnet/website-feedback#271]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### URL

https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor#:~:text=Blazor%20is%20a%20modern%20front,can%20deliver%20great%20web%20experiences.

### Browser

Microsoft Edge

### Description

I dont see nay fucking things on the left side, i use horizontal tab.

![Image](https://github.com/user-attachments/assets/f5ae7fb8-862b-49bc-9fb7-2a3309a59c5a)

**Comment by mairaw** [comment]
Thanks for reporting this issue. It seems this only happens when the site comes with this text highlighted from search engine. I managed to reproduce the problem.

If you visit https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor, then the site opens as expected on mobile. I'll log an issue for my team to work on this.

**Comment by mairaw** [comment]
Can you let us know what kind of device you're using here?

**Comment by mairaw** [comment]
The issue has been resolved. Thanks for reporting.
