### ISSUE TITLE
I can't create a c# cosnole app, using c# dev kit

### ISSUE THREAD

**Issue by leoleoleo57** [dotnet/website-feedback#76]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

I tried to create a new console app, using c# dev kit in visual studio code. 
I followed the steps on Microsoft's page, but I get the following error: 
![image](https://github.com/dotnet/website-feedback/assets/109578410/b9343fce-f773-4998-88ed-b476bd3c9a00)

I aready installed the .net sdk:  
![image](https://github.com/dotnet/website-feedback/assets/109578410/4dc6dce4-e952-4d8d-9df2-e96a5026189e)

And I also installed and connected my account to c# dev kit:
![image](https://github.com/dotnet/website-feedback/assets/109578410/7914daec-08a6-46c4-88c4-44cd08cf95f2)

Why is the error?

**Comment by mairaw** [comment]
Can you also share what `dotnet --info` returns?

**Comment by sunhaolin** [comment]
+1

**Comment by mairaw** [comment]
Thank you @leoleoleo57.

The screenshot shows that you have a mix of x86 and x64 installations on your machine. There was a bug that was fixed in newer releases related to the PATH.

Please run `where.exe dotnet` and see what it returns. If x86 is first and your machine is x64, please use these instructions to fix your PATH:
https://github.com/dotnet/core/issues/5962#issuecomment-780084535

@sunhaolin I might need some information from your system to be able to help you.

**Comment by sunhaolin** [comment]
![image](https://github.com/dotnet/website-feedback/assets/6194896/cfd8982c-6127-4efb-a3cb-d74a8719c2dd)

**Comment by mairaw** [comment]
Great to hear @leoleoleo57. 

@sunhaolin I think in your case it would be best to open an issue on the C# dev kit repo: https://github.com/microsoft/vscode-dotnettools/issues
Before you do that, if you create an app via terminal, does it work?
dotnet new console -o MyConsoleApp

Just wondering if it's an installation problem or C# Dev Kit one.

**Comment by mairaw** [comment]
Closing due to the lack of information for more than 2 months.
